apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
env:
  - name: DB_HOST
    value: interview-app-database
  - name: DB_USER
    value: postgres
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: interview-app-database-secret
        key: postgres-password
  - name: DB_NAME
    value: interview_db