frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: latest

backend:
  replicaCount: 1
  image:
    repository: backend
    tag: latest
    pullPolicy: Always

database:
  image:
    repository: postgres
    tag: "13"
  password: password